# Generated by Django 6.0 on 2025-12-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='BRL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='dashboard.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('BR_STOCK', 'Ações BR (Swing)'), ('BR_DAYTRADE', 'Day Trade (Qualquer Ativo BR)'), ('BR_FII', 'Fundos Imobiliários (FII)'), ('BR_ETF', 'ETF Brasileiro'), ('US_STOCK', 'Stocks/REITs/ETFs EUA'), ('CFD', 'CFD (Forex/Índices/Commodities)'), ('CRYPTO', 'Criptomoedas (Exchange Ext.)')], default='BR_STOCK', max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=5, default=1, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=15, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_result', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_sale_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='PTAX do dia do fechamento', max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Em Aberto'), ('CLOSED', 'Fechado')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='dashboard.portfolio')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='dashboard.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Primeiro dia do mês')),
                ('sales_volume_br_swing', models.DecimalField(decimal_places=2, default=0.0, help_text='Se < 20k, isento', max_digits=15)),
                ('result_br_daytrade', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('result_br_swing', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('result_br_fii', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_due_br', models.DecimalField(decimal_places=2, default=0.0, help_text='DARF a pagar este mês', max_digits=15)),
                ('result_offshore', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_provision_offshore', models.DecimalField(decimal_places=2, default=0.0, help_text='Provisão para ajuste anual (15%)', max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
