# Generated by Django 6.0 on 2025-12-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Primeiro dia do mês de referência')),
                ('total_gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_losses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
