# Generated by Django 6.0 on 2025-12-15 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeentry',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradeentry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradeexit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradeexit',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='sales_volume_br_swing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='tax_due_br',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='tax_provision_offshore',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_type',
            field=models.CharField(choices=[('BR_STOCK', 'Ações BR (Swing)'), ('BR_DAYTRADE', 'Day Trade (Índice/Dólar/Ação)'), ('BR_FII', 'Fundos Imobiliários (FII)'), ('BR_ETF', 'ETF Brasileiro'), ('US_STOCK', 'Stocks/REITs/ETFs EUA'), ('CFD', 'CFD (Forex/Índices/Commodities)'), ('CRYPTO', 'Criptomoedas')], default='BR_STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
