# Generated by Django 6.0 on 2025-12-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='dashboard.strategy'),
        ),
    ]
